[package]
name = "minstant"
version = "0.0.0"
authors = ["zhongzc"]
edition = "2018"

[dependencies]
spinlock = "0.1"

[target.'cfg(not(target_os = "wasi"))'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "wasi")'.dependencies]
wasi = "0.10.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "now"
harness = false
