[package]
name = "minstant"
version = "0.0.1"
authors = ["zhongzc"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
ctor = "0.1.20"

[workspace]
members = [ "minstant_macro" ]

[target.'cfg(not(target_os = "wasi"))'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "wasi")'.dependencies]
wasi = "0.7"

[dev-dependencies]
criterion = "0.3"
rand = "*"

[[bench]]
name = "now"
harness = false
