[package]
name = "minstant_macro"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1", features = ["full", "extra-traits"] }
quote = "1"
proc-macro-error = "1.0"

[dev-dependencies]
minstant = { path = ".." }
